name = "autonomous-recovery-pipeline"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "autonomous-recovery-db"
database_id = "313d9594-51b8-4435-99a4-e74917a6c14a"

[vars]
GMAIL_USER = "abhishek.nitj.002@gmail.com"
GMAIL_APP_PASSWORD = ""
RECIPIENT_TEST_EMAIL = "abhishekmkumar676@gmail.com"
